// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/pessoa.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RequisicaoPessoa struct {
	Nome string `protobuf:"bytes,1,opt,name=nome" json:"nome,omitempty"`
}

func (m *RequisicaoPessoa) Reset()                    { *m = RequisicaoPessoa{} }
func (m *RequisicaoPessoa) String() string            { return proto1.CompactTextString(m) }
func (*RequisicaoPessoa) ProtoMessage()               {}
func (*RequisicaoPessoa) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *RequisicaoPessoa) GetNome() string {
	if m != nil {
		return m.Nome
	}
	return ""
}

func (c *Server) VerNome(ctx context.Context, requisicao *RequisicaoPessoa) (*RetornoPessoa, error) {

	var nomeCompleto *RetornoPessoa = &RetornoPessoa{
		NomeResultado: requisicao.Nome + " da Silva",
	}

	return nomeCompleto, nil
}

type RetornoPessoa struct {
	NomeResultado string `protobuf:"bytes,1,opt,name=nomeResultado" json:"nomeResultado,omitempty"`
}

func (m *RetornoPessoa) Reset()                    { *m = RetornoPessoa{} }
func (m *RetornoPessoa) String() string            { return proto1.CompactTextString(m) }
func (*RetornoPessoa) ProtoMessage()               {}
func (*RetornoPessoa) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *RetornoPessoa) GetNomeResultado() string {
	if m != nil {
		return m.NomeResultado
	}
	return ""
}

func init() {
	proto1.RegisterType((*RequisicaoPessoa)(nil), "proto.RequisicaoPessoa")
	proto1.RegisterType((*RetornoPessoa)(nil), "proto.RetornoPessoa")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AddServicePessoa service

type AddServicePessoaClient interface {
	VerNome(ctx context.Context, in *RequisicaoPessoa, opts ...grpc.CallOption) (*RetornoPessoa, error)
}

type addServicePessoaClient struct {
	cc *grpc.ClientConn
}

func NewAddServicePessoaClient(cc *grpc.ClientConn) AddServicePessoaClient {
	return &addServicePessoaClient{cc}
}

func (c *addServicePessoaClient) VerNome(ctx context.Context, in *RequisicaoPessoa, opts ...grpc.CallOption) (*RetornoPessoa, error) {
	out := new(RetornoPessoa)
	err := grpc.Invoke(ctx, "/proto.AddServicePessoa/verNome", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AddServicePessoa service

type AddServicePessoaServer interface {
	VerNome(context.Context, *RequisicaoPessoa) (*RetornoPessoa, error)
}

func RegisterAddServicePessoaServer(s *grpc.Server, srv AddServicePessoaServer) {
	s.RegisterService(&_AddServicePessoa_serviceDesc, srv)
}

func _AddServicePessoa_VerNome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequisicaoPessoa)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServicePessoaServer).VerNome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddServicePessoa/VerNome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServicePessoaServer).VerNome(ctx, req.(*RequisicaoPessoa))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddServicePessoa_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AddServicePessoa",
	HandlerType: (*AddServicePessoaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "verNome",
			Handler:    _AddServicePessoa_VerNome_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pessoa.proto",
}

func init() { proto1.RegisterFile("proto/pessoa.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x48, 0x2d, 0x2e, 0xce, 0x4f, 0xd4, 0x03, 0x73, 0x84, 0x58, 0xc1, 0x94, 0x92,
	0x1a, 0x97, 0x40, 0x50, 0x6a, 0x61, 0x69, 0x66, 0x71, 0x66, 0x72, 0x62, 0x7e, 0x00, 0x58, 0x81,
	0x90, 0x10, 0x17, 0x4b, 0x5e, 0x7e, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98,
	0xad, 0x64, 0xca, 0xc5, 0x1b, 0x94, 0x5a, 0x92, 0x5f, 0x94, 0x07, 0x53, 0xa4, 0xc2, 0xc5, 0x0b,
	0x92, 0x08, 0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x49, 0x4c, 0xc9, 0x87, 0xaa, 0x46, 0x15, 0x34, 0xf2,
	0xe1, 0x12, 0x70, 0x4c, 0x49, 0x09, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x85, 0xea, 0xb4, 0xe0,
	0x62, 0x2f, 0x4b, 0x2d, 0xf2, 0xcb, 0xcf, 0x4d, 0x15, 0x12, 0x87, 0x38, 0x46, 0x0f, 0xdd, 0x09,
	0x52, 0x22, 0x70, 0x09, 0x24, 0x3b, 0x93, 0xd8, 0xc0, 0x82, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x26, 0xa6, 0xf5, 0x59, 0xd0, 0x00, 0x00, 0x00,
}
